import React from 'react'

export default function laoding() {
  return (
    <>
<div className='bg-white'>

    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
    <div>laoding</div>
</div>
    </>
  )
}
